language: node_js

node_js: --lts

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - git config --global user.name 'JounQin'
  - git config --global user.email 'admin@1stg.me'

install: yarn --frozen-lockfile

script:
  - yarn lint
  - yarn demo
  - 'if [[ $TRAVIS_BRANCH = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash sync.sh; fi'
